services:
  - type: web
    name: pomego-autofunnel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autofunnel-db
          property: connectionString

databases:
  - name: autofunnel-db
    plan: free
